.TH build-qmail 1
.SH NAME
build-qmail \- build binary qmail package
.SH SYNTAX
.B build-qmail

.SH DESCRIPTION
This script unpacks the qmail 1.0.3 source into a directory, and
compiles it to produce a binary qmail-1.0.3??.deb file.

The directory where this is done will end up containing the source
and package files for the $package binary package, along with a
directory containing the unpacked source.

.B WARNING:
There have been reports of undesired behavior when attempting to
build qmail in a directory on a tmpfs based filesystem.  Please do
not try to build on an tmpfs filesystem.
