#!/bin/sh

cat <<EOF

  Note, this "newaliases" command does not make use of the contents of:
    /etc/aliases
  because it is in fact just a wrapper for qmail-newu, which uses:
    /etc/qmail/users/assign
  for a similar purpose.

  See the man page for qmail-newu(8) for more details

EOF
exec /usr/sbin/qmail-newu
