#!/usr/bin/perl

$hassmtpininetd = 0;
if ( -e "/etc/inetd.conf" ) {
    system('grep "^ *[^#].*\<smtp\>" /etc/inetd.conf');
    if ( ! $? ) {
        $hassmtpininetd = 1;
    }
}

require DebianNet if ( $hassmtpininetd );

$| = 1;

$action = shift;

if ( $action eq 'failed-upgrade' ) {
    exit 1;
}

if ( $action eq 'upgrade'  or $action eq 'deconfigure' ) {
    system("/etc/init.d/qmail stop");
    exit $? if $?;
    DebianNet::disable_service('smtp') if ( $hassmtpininetd );
    exit 0;
}

if ( $action eq 'remove' ) {
    # Remove qmail-smtpd from inetd.conf
    DebianNet::remove_service('smtp\s+stream\s+tcp\s+nowait\s+qmaild.*/usr/sbin/qmail-smtpd') if ( $hassmtpininetd );;
    
    # Stop qmail process.
    system("/etc/init.d/qmail stop");
    exit $? if $?;
}

exit 0;
