.TH checkpassword 8
.SH NAME
checkpassword \- check a password
.SH SYNOPSIS
.B checkpassword
.I subprogram
[
.I args ...
]
.SH DESCRIPTION
.B checkpassword
reads descriptor 3 through end of file
and then closes descriptor 3.
There must be at most 512 bytes of data before end of file.

The information supplied on descriptor 3
is a login name terminated by \e0,
a password terminated by \e0,
a timestamp terminated by \e0,
and possibly more data.
There are no other restrictions on
the form of the login name, password, and timestamp.

If the password is unacceptable,
.B checkpassword
exits 1.
If
.B checkpassword
is misused,
it may instead exit 2.
If there is a temporary problem checking the password,
.B checkpassword
exits 111.

If the password is acceptable,
.B checkpassword
uses
.B execvp
to run
.B subprogram
with the given arguments.
.SH "CHECKPASSWORD-COMPATIBLE TOOLS"
There are other tools that offer the same interface as
.BR checkpassword .
Applications that use
.B checkpassword
are encouraged to take the
.B checkpassword
name as an argument,
so that they can be used with different
.BR checkpassword -compatible
tools.

Note that these tools do not follow the
.B getopt
interface.
Optional features are controlled through
(1) the tool name and
(2) environment variables.
.SH "THE PASSWORD DATABASE"
.B checkpassword
checks the login name and password against
.BR /etc/passwd ,
using the operating system's
.B getpwnam
and
.B crypt
functions.
It rejects accounts with empty passwords.
It ignores the timestamp.

Other
.BR checkpassword -compatible
tools have different interpretations of
login names, passwords, and timestamps.
Both the login name and the password
should be treated as secrets by the application calling
.BR checkpassword ;
the only distinction is for administrative convenience.
The timestamp should include any other information
that the password is based on;
for example, the challenge in a challenge-response system such as APOP.

.B WARNING:
.B getpwnam
is inherently unreliable.
It fails to distinguish between temporary errors and nonexistent users.
Future versions of
.B getpwnam
should return ETXTBSY to indicate temporary errors
and ESRCH to indicate nonexistent users.
.SH "PROCESS-STATE CHANGES"
Before invoking
.BR subprogram ,
.B checkpassword
sets up
.BR $USER ,
.BR $HOME ,
.BR $SHELL ,
its supplementary groups,
its gid,
its uid,
and its working directory.

Other
.BR checkpassword -compatible
tools may make different changes to the process state.
These effects must be documented;
applications will differ in their requirements.
.SH "VERSION"
This documentation describes
.B checkpassword
version 0.80.
See
.B http://pobox.com/~djb/checkpwd.html
for updates.
.SH "SEE ALSO"
getpwnam(3),
crypt(3)
